services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  api:
    container_name: api
    image: 16-alpine
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    environment:
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    command: ["npm", "run", 'serve']

  b-band-transponder:
    container_name: b-band-transponder
    image: 16-alpine
    build:
      context: ./b-band-transponder
    volumes:
      - ./b-band-transponder:/usr/src/app
    environment:
      API_PORT: ${SOCKET_PORT}
    ports:
      - ${SOCKET_PORT}:${SOCKET_PORT}
    command: ["npm", "run", 'ignition']
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  api:
  b-band-transponder: