services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api:
    container_name: api
    image: 16-alpine
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/app/node_modules
    environment:
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    command: sh boot.sh

  b-band-transponder:
    container_name: b-band-transponder
    image: 16-alpine
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./b-band-transponder
    volumes:
      - ./b-band-transponder:/usr/src/app
    environment:
      API_PORT: ${SOCKET_PORT}
    ports:
      - ${SOCKET_PORT}:${SOCKET_PORT}
    command: ["npm", "run", 'ignition']
  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - 8080:8080